# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='note_title',
        ),
    ]
