# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='brief',
            field=models.CharField(max_length=100),
        ),
    ]
